[project]
name = "data-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy==1.26.4",
    "pandas>=2.2.3",
    "pyarrow>=19.0.1",
    "pyspark>=3.5.5",
    "pytest>=8.3.5",
    "ruff>=0.11.3",
]
